import Header from "./components/header/header";
import Layout from "./components/layout/layout";
import PageLayout from "./components/layout/pageLayout";
import Sidebar from "./components/sidebar/sidebar";
import "./globals.css";
import { AuthProvider } from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Layout>
            <Header />
            <div className="flex h-screen w-full">
              <Sidebar />
              <PageLayout>{children}</PageLayout>
            </div>
          </Layout>
        </AuthProvider>
      </body>
    </html>
  );
}
